name: EduardCurso
description: Sistemas feitos no Curso do Eduard
main: net.eduard.curso.CursoEduard
version: 1.0
authors: [Eduard]
depend: [EduardAPI]
website: https://www.youtube.com/user/EduTutoriaisHD
commands:
  caixa:
  rank:
    description: Subir de Rank
    usage: /<command>
    aliases: [rankup]
  setspawn:
    description: Setar o Spawn
    usage: /<command>
  spawn:
    description: Ir ao Spawn
    usage: /<command>
  cash:
    description: Teste
    usage: Digite /cash
  login:
    description: Teste
    usage: Digite /cash
  register:
    aliases: [registrar]
    description: Registrar sua Conta
    usage: /<command> <senha> <senhaconfirma>
  setwarp:
    aliases: [createwarp]
    description: Setar uma Warp
    usage: /<command> <warp>
  deletewarp:
    aliases: [delwarp]
    description: Deletar uma Warp
    usage: /<command> <warp>
  warps:
    aliases: [warplist]
    description: Listar as Warps
    usage: /<command>
  warp:
    description: Teleportar ate uma Warp
    aliases: [local]
    usage: /<command> <warp>
  delay:
  timer:
  cooldown:
  money:
    aliases: [dinheiro]
  

