name: EduardCurso
description: Sistemas feitos no Curso do Eduard
main: net.eduard.curso.Main
version: ${project.version}
authors: [Eduard]
depend: [EduardAPI]
website: https://www.youtube.com/user/EduTutoriaisHD
commands:
  settag:
    aliases: [setartag]
  report:
    aliases: [reportar]
  reports:
    aliases: [reportados]
  caixa:
    aliases: [caixas]
  rank:
    description: Subir de Rank
    usage: /<command>
    aliases: [rankup]
  setspawn:
    description: Setar o Spawn
    usage: /<command>
  spawn:
    description: Ir ao Spawn
    usage: /<command>
  cash:
    description: Sistema de Cash
    usage: Digite /cash
  login:
    aliases: [logar]
    description: Entrar na conta
    usage: /<command> <senha>
  register:
    aliases: [registrar]
    description: Registrar sua Conta
    usage: /<command> <senha> <senhaconfirma>
  setwarp:
    aliases: [createwarp]
    description: Setar uma Warp
    usage: /<command> <warp>
  deletewarp:
    aliases: [delwarp]
    description: Deletar uma Warp
    usage: /<command> <warp>
  warps:
    aliases: [warplist]
    description: Listar as Warps
    usage: /<command>
  warp:
    description: Teleportar ate uma Warp
    aliases: [local]
    usage: /<command> <warp>
  money:
    aliases: [dinheiro]
  # Comandos abaixo de sistemas isolados
  tabcomplete:
    aliases: [completes]
  delay:
  timer:
    description: Inicia um Timer ou seja um repetidor
  timer2:
    description: Igual comando timer, a diferenca que o timer esta em classe separada
  cooldown1:
    description: Ao fizer este comando ficara em cooldown nao podendo digitar novamente
  cooldown2:
    description: Igual comando cooldown1, a diferenca mostra o tempo restante para sair do cooldown  


